### ISSUE TITLE
Resolver should support JSONC syntax of tsconfig.json

### ISSUE THREAD

**Issue by nartallax** [yakovlev-alexey/parcel-resolver-ts-base-url#6]
Typescript compiler (and the rest of toolchain) assumes that `tsconfig.json` is JSONC.
JSONC allows for neat features like comments, or trailing commas in arrays.

This resolver, hovewer, assumes that `tsconfig.json` is JSON; that means it will break on comments and other stuff.

For example, following part of `tsconfig.json` breaks the parsing in this resolver for several reasons:

```jsonc
"compilerOptions": {
  "outDir": "js",
  "rootUrl": "./src/",
  "baseUrl": "./src/",
  // this one is for beatiful imports!
  "paths": {
      "*": [
          "./*",
      ]
  },
}
```

**Comment by yakovlev-alexey** [comment]
Fixed in [1.3.1](https://github.com/yakovlev-alexey/parcel-resolver-ts-base-url/tree/v1.3.1). Thank you for your contribution!
